version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - emptyStringTest
        - hugeParam
        - httpNoBody
        - paramTypeCombine
        - rangeValCopy
        - unnamedResult
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
